### ISSUE TITLE
Feature: multiple partials in a folder

### ISSUE THREAD

**Issue by evanbutera** [BrianDGLS/node-hologram#5] opened 2016-03-22 12:57 UTC
If docs are written on partials contained in a folder, the resulting html file will contain only the last partial docs.
It could be helpful to allow docs to be written inside partials, generate example html files from the partial name and output the navigation as nested lists of collection (folder) element (file name)

**Comment by evanbutera** [comment] 2016-03-23 09:15
This also can partially be solved by https://github.com/BrianDGLS/node-hologram/issues/3

**Comment by BrianDGLS** [comment] 2016-03-23 12:48
Is this an issue caused by the fact that you need to specify the folder that hologram looks in? 

eg: `dir: ['/path/to/dir', '/path/to/other']`

I feel like doing a recursive search maybe a better solution, eg: just pass in the parent directory and search for all files ending with `.scss` in all sub folders.

I'll take a look at this and see how it works compared to defining the folders beforehand.

Relevant to (#3)

**Comment by evanbutera** [comment] 2016-03-23 13:14
Fact is, sass architecture using lot of partials is quite common.
That means having lot of partials in semantically named folders 

e.g.: http://sass-guidelin.es/#architecture

meaning that in the actual iteration hologram will compile a single folder-example.html for each folder - instead of having a single file-example.html for each file.

ie
`
|- modules/
|  |-_module-one.scss
|  |-_module-two.scss
`
gives a single
`
modules-example.html
`
containing only the last (alphabetically) scss file doc.
maybe this depend on the string used to generate the file name.

I think it would be suboptimal to configure the path for each and every file.
A recursive search like in #3 could be a nice solution, obtaining an output similar to `folder--file.html`
ie
`
modules--module-one.html
modules--module-two.html
`

**Comment by BrianDGLS** [comment] 2016-03-23 13:52
I can see what you mean.

This one is quite tough to implement.

What I will do for now is try a recursive search which looks in any file in the parent or it's subfolders that has the correct extension. Bare in mind this can work for multiple file types.

This will mean that the folders specified in `dir: ['/path/to/dir', '/path/to/other']` are starting points from which a recursive search will begin.

The docs will need updated once this is implemented.

**Comment by evanbutera** [comment] 2016-03-23 14:05
I guessed from the code it could be hard to implement.
On a second thought this could also be achived mirroring the source folders structure

ie
```
|-modules/
|  |-module-one.html
|  |-module-two.html
```

**Comment by evanbutera** [comment] 2016-03-23 14:58
more on this
```
styles: {
        dir: [
            '/src/scss/system/image', // _image.scss
            '/src/scss/system/text', // _text.scss
            '/src/scss/system/table', // _table.scss
            '/src/scss/layout/global',
            '/src/scss/layout/mediaObject',
            '/src/scss/modules/paragraph/countdown',
            '/src/scss/modules/paragraph/intro',
            '/src/scss/modules/paragraph/media',
            '/src/scss/modules/paragraph/person',
            '/src/scss/modules/paragraph/simple',
            '/src/scss/theme/button'
        ],
        main: './assets/main.css'
    },
```

even splitting partials into sub folders, hologram produces only a single example file, tied to the parent folder

eg:

`system-example.html` while expecting `image-example.html`

**Comment by evanbutera** [comment] 2016-03-23 15:08
Reached some kind of solution:
it all depends on the dot inside partial names.

`_system.image.scss` results in system-example.html

`_system-image.scss` results in system-image.html

**Comment by BrianDGLS** [comment] 2016-03-23 20:09
> _system.image.scss results in system-example.html
> 
> _system-image.scss results in system-image-example.html

This actually explains a lot I was confused to what the main issue was here. Luckily this is an easy fix. It's caused by the way I an currently formatting the filenames. I won't be able to add the fix for it till the weekend, however it is something that can be easily solved.

Will update when in progress.

**Comment by BrianDGLS** [comment] 2016-03-29 09:50
@evanbutera Fix for this merged into develop branch.

Would you mind testing?

**Comment by evanbutera** [comment] 2016-03-29 12:19
I'll give it a spin and let you know.

**Comment by evanbutera** [comment] 2016-03-29 12:22
working.

**Comment by BrianDGLS** [comment] 2016-03-29 12:40
@evanbutera Thanks, closing ticket.

**Closed by BrianDGLS** 2016-03-29 12:40 UTC
