### ISSUE TITLE
Feature: docs order parameter

### ISSUE THREAD

**Issue by evanbutera** [BrianDGLS/node-hologram#6] opened 2016-03-22 13:19 UTC
At the moment docs are ordered in an alphabetical way.

It would be useful to allow a parameter inside doc definition to give them a weight attribute to alter the output order.

**Comment by BrianDGLS** [comment] 2016-03-22 20:33
This is an interesting one, how do you see this working?

It would be possible to add an option that assigned a component of a certain name to a position in the list,  eg:

```
"customOrder": [{"header": 1},  {"footer": 2}]
```

This would result in `header` being the first item on the list and `footer` being the second. Everything else would then come after in the default alphabetical order.

**Comment by evanbutera** [comment] 2016-03-23 09:04
Working a lot with scss partials, I was thinking of using a known char sequence in the scss doc to assign a weight, then order elements by parent folder > weight > alphabetical order.

```
/* doc
%*1*%
...
*/
```

For the list order I would suggest to state in the docs that folders are processed in the given order - as they are now. This just makes more sense.

Ideally the opt customOrder could work marvels if 

`styles: { 
    dir: 'path/to/dir',
    main: 'path/to/main.css'
}`

could accept just the base scss folder and delegate to customOrder the folder/files order, leaving the others to be sorted alphabetically.

**Comment by evanbutera** [comment] 2016-03-27 15:04
More on this.

was thinking about something like
```
/* doc
%*scss group*% // string
%-scss weight-% // numeric
...
*/
```

were scss group can be used to define an order of semanically ordered styles, and weight as a way to order files in the page while inside a single group.

i.e
```
Layout
- media object // has w 1, group layout
- simple // has w 1, group layout
- base box // has w undefined - tho using alphabetical order - , group layout
Buttons
- base // group buttons
```

**Comment by evanbutera** [comment] 2016-03-27 20:08
mind that, groups order can be left alphabetical or overridden from opts or - should be a nice thing - assume that a `global` group will be the first one to be displayed - the one intended to contain colors, fonts and other setup variables - and others should be left as alphabetical or, eventually overridden

I know complexity will rise, but also versatility

Thoughts?

**Comment by BrianDGLS** [comment] 2016-03-28 10:26
The problem is that I have no reliable way to extract information from the markdown.

In order to add the above functionality I would have to write a regex to extract the information. I don't feel that this is a good solution.

It would be much more efficient and reliable to keep all the config inside the the `options` json object or in a separate json file.

Do you have any suggestions as to how this could be added to the json?

**Comment by evanbutera** [comment] 2016-03-29 07:33
I've been messing around wt the code for some time.
My best guess is that, providing documentation, the end user can be held responsible for the correct setup of docs.

This can allow the use of a regex to check for a defined code block in a specific position, ie

```
/*doc
---
group : xyz
weight: 123
---
__some markdown__
```

basically an alteration to extractExample function will do

**Comment by BrianDGLS** [comment] 2016-03-29 08:11
Yes, it's totally possible. I'm just not confident in using a regex to parse Markdown, I can see it being unreliable.

What I will do is fix the other outstanding tickets and pull requests first. Which will allow me to make a new release.

After that is done I'll implement the above on the develop branch.

**Comment by BrianDGLS** [comment] 2016-04-09 18:51
Order can now be added via meta data.

Merged in to develop as part of https://github.com/BrianDGLS/node-hologram/pull/27

See https://github.com/BrianDGLS/node-hologram/tree/develop#meta-data

**Closed by BrianDGLS** 2016-04-09 18:51 UTC
